name: SquadSentinel CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ] 

jobs:
  test_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Instalam librăriile necesare
        pip install pandas matplotlib seaborn openpyxl statsbombpy pytest
        
    - name: Run Pipeline Sanity Check
      run: |
        cd SRC
        python main.py --match-id 303430 --team "Barcelona"
